apiVersion: v1
kind: Service
metadata:
  name: demo1-app-service
  namespace: yassen_hamdy
  labels:
    app: demo1-app
    owner: yassen_hamdy
spec:
  type: NodePort
  selector:
    app: demo1-app
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      nodePort: 30090
