apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yassen-hamdy-project
  namespace: argocd
  labels:
    owner: yassen_hamdy
spec:
  description: ArgoCD project for yassen hamdy - deploy to yassen_hamdy namespace
  sourceRepos:
    - '*'
  destinations:
    - namespace: yassen_hamdy
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
